### ISSUE TITLE
[Feat] 허브 생성 기능

### ISSUE THREAD

**Issue by muncool39** [muncool39/msa-project#23]
## Description

허브 정보를 생성하는 기능을 개발합니다.

## TODO

- [x] 허브 생성 요청 객체
- [x] 사용자 권한이 MASTER 인지 권한 확인
- [x] 오류 상황에 맞는 에러 코드 추가
- [x] 응답 객체 생성
