### ISSUE TITLE
[Fix] 허브 생성 시 허브 관리자가 저장되도록 수정

### ISSUE THREAD

**Issue by muncool39** [muncool39/msa-project#39]
## Description

허브 생성 시 

## TODO

- [x] 허브 엔티티에 유저 연결
- [x] 요청 객체에 관리자 id 추가
- [x] 해당 유저가 허브 관리자 권한인지 확인
