### ISSUE TITLE
[Fix] 유저 정보에 소속 정보가 저장되도록 변경

### ISSUE THREAD

**Issue by muncool39** [muncool39/msa-project#46]
## Description

유저 엔티티에 소속 허브 정보가 저장될 수 있도록 수정합니다.

## TODO

- [x] 허브 생성시 관리자 정보 받지 않도록 변경
- [x] 허브 서비스에 관리자 등록 api 생성
- [x] 유저 엔티티에 필드 추가
- [x] 유저 단건 조회시 해당 정보가 포함되도록 응답 객체 수정

## Reference

- 12/13 slack 의견

**Comment by jhbreeze** [comment]
투두리스트 보고 궁금한 사항이 있어 의견 남깁니다!
허브 엔티티에서 매니저 아이디를 제외한다는게, 허브 서비스에 허브 아이디로 정보 요청을 조회하면 담당 허브 매니저 아이디는 응답에서 제외하도록 수정하는걸까요??

**Comment by muncool39** [comment]
@jhbreeze 그 의미가 맞긴 합니다! 사실 고민중인 내용이긴 한데
한 허브를 관리할 수 있는 유저가 여러명일 경우 허브쪽에 관리자 정보는 저장하지 않아야 될 것 같아서 일단 작성했습니다 딱히 요구사항에 정확하게 지정된게 없어서 고민되는 내용이긴 해요 1:1 이라면 양쪽에 다 저장해도 될 것 같긴 한데 
혹시 어떻게 생각하시나요?

**Comment by jhbreeze** [comment]
@muncool39 msa 구조라서 계속 서비스들을 호출하게 되는데, 양쪽에서 관리하면 서비스 호출을 줄일 수 있는 좋은 방안인 것 같아요!

**Comment by muncool39** [comment]
@jhbreeze 그럼 허브당 관리자는 한명인걸로 구현하도록 하겠습니다! 의견 감사합니다! 👍
