### ISSUE TITLE
[Feat] 허브 루트 수정 기능

### ISSUE THREAD

**Issue by muncool39** [muncool39/msa-project#84]
## Description
허브 루트를 수정하는 기능을 개발합니다.

## TODO
- [x] 권한 확인
- [x] 수정 범위 정하기
- [x] 일부 수정 가능하도록 하기
- [x] API 테스트
- [x] DB 반영 확인

## Additional context
