### ISSUE TITLE
[Feat] 허브 경로 조회에 캐싱 적용

### ISSUE THREAD

**Issue by muncool39** [muncool39/msa-project#89]
## Description
허브 경로 조회 시 캐싱 적용되도록 수정하기

## TODO
- [x] 레디스 설정 추가
- [x] 캐시 설정 추가
- [x] 서비스에 캐싱 적용
## Additional context
